services:
  # Laravel Application
  app:
    build: .
    container_name: erecruitment_laravel_app
    restart: unless-stopped
    ports:
      - "8001:8000"  # Using port 8001 to avoid conflict with admin app
    env_file:
      - docker.env
    volumes:
      - .:/var/www/html
      - vendor_data:/var/www/html/vendor
      - node_modules_data:/var/www/html/node_modules
      - build_data:/var/www/html/public/build
    networks:
      - erecruitment_laravel_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: >
      sh -c "
        sleep 15 &&
        composer install --no-interaction &&
        npm install &&
        php artisan key:generate --force &&
        php artisan config:clear &&
        php artisan config:cache &&
        php artisan serve --host=0.0.0.0 --port=8000
      "

volumes:
  vendor_data:
  node_modules_data:
  build_data:

networks:
  erecruitment_laravel_network:
    driver: bridge
  erecruitment-laravel-user_erecruitment_network:
    external: true