services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: erecruitment_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: erecruitment
      MYSQL_USER: erecruitment_user
      MYSQL_PASSWORD: erecruitment_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - erecruitment_network
    command: --default-authentication-plugin=mysql_native_password

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: erecruitment_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - erecruitment_network

  # Laravel Application
  app:
    build: .
    container_name: erecruitment_app
    restart: unless-stopped
    ports:
      - "8001:8000"  # External port 8001, internal port 8000
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=erecruitment
      - DB_USERNAME=erecruitment_user
      - DB_PASSWORD=erecruitment_password
    volumes:
      - .:/var/www/html
      - vendor_data:/var/www/html/vendor
      - node_modules_data:/var/www/html/node_modules
      - build_data:/var/www/html/public/build
    depends_on:
      mysql:
        condition: service_started
    networks:
      - erecruitment_network
    # Remove custom command, let Dockerfile handle it
    # The Dockerfile already has CMD to start Laravel server

volumes:
  mysql_data:
  vendor_data:
  node_modules_data:
  build_data:

networks:
  erecruitment_network:
    driver: bridge
