services:
  # Laravel Application - menggunakan database yang sudah ada
  app:
    build: .
    container_name: erecruitment_general_user_app
    restart: unless-stopped
    ports:
      - "8001:8000"  # Port berbeda dari admin (8000)
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=erecruitment_mysql  # Menggunakan container MySQL yang sudah ada
      - DB_PORT=3306
      - DB_DATABASE=erecruitment
      - DB_USERNAME=erecruitment_user
      - DB_PASSWORD=erecruitment_password
    volumes:
      - .:/var/www/html
      - vendor_data:/var/www/html/vendor
      - node_modules_data:/var/www/html/node_modules
      - build_data:/var/www/html/public/build
    networks:
      - erecruitment_network  # Menggunakan network yang sudah ada
    command: >
      sh -c "
        sleep 10 &&
        composer install &&
        npm install &&
        php artisan key:generate --force &&
        php artisan config:cache &&
        php artisan migrate --force &&
        php artisan serve --host=0.0.0.0 --port=8000
      "

volumes:
  vendor_data:
  node_modules_data:
  build_data:

networks:
  erecruitment_network:
    external: true
    name: e-recruitment-laravel-admin_erecruitment_network