name: Deploy Laravel to VPS with Nginx

on:
  push:
    branches:
      - main   # Auto deploy kalau ada push ke branch main
 
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Copy source code to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "."
          target: "/var/www/e-recruitment"

      - name: Deploy Laravel app
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/e-recruitment
            
            # Install/update Composer dependencies
            composer install --no-dev --optimize-autoloader
            
            # Run Laravel optimization commands
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan optimize
            
            # Set proper permissions for Laravel
            chown -R www-data:www-data storage bootstrap/cache
            chmod -R 775 storage bootstrap/cache
            
            # Set proper permissions for entire application
            chown -R www-data:www-data /var/www/e-recruitment
            chmod -R 755 /var/www/e-recruitment
            
            # Restart nginx and php-fpm
            systemctl restart nginx
            systemctl restart php8.3-fpm
            
            # Clear any existing caches
            php artisan cache:clear
            php artisan config:clear